# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory to /app
WORKDIR /app

# Copy the Python scripts into the container
COPY main.py .
COPY semester.py .
COPY university.py .
COPY course.py .

# Run main.py when the container launches
CMD ["python", "main.py"]
#terminal
#docker build -t allocation-app .
#docker run allocation-app


